/* Generated By:JJTree: Do not edit this line. ASTArithmeticFactor.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTArithmeticFactor extends SimpleNode {

	private String sign = "";
	private String result;

	public ASTArithmeticFactor(int id) {
		super(id);
	}

	public ASTArithmeticFactor(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Override
	public void dump(String prefix) {
		super.dump(prefix);
		System.out.println("ASTArithmeticFactor result=" + result);
	}

}
/* JavaCC - OriginalChecksum=0316633285c388c2b58bcc5b5e8e6124 (do not edit this line) */
