/* Generated By:JJTree: Do not edit this line. ASTArithmeticPrimary.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTArithmeticPrimary extends SimpleNode {

	private String result = "";

	public ASTArithmeticPrimary(int id) {
		super(id);
	}

	public ASTArithmeticPrimary(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getResult() {
		return result;
	}

	@Override
	public void dump(String prefix) {
		super.dump(prefix);
		System.out.println("ASTArithmeticPrimary result=" + result);
	}

	public void setResult(String result) {
		System.out.println("ASTArithmeticPrimary: result=" + result);
		dump("");
//		System.out.println("ASTArithmeticPrimary: this=" + this.dump(""));
		this.result = result;
	}

}
/* JavaCC - OriginalChecksum=ef8cc4a7b1426908e1528b745e835ad8 (do not edit this line) */
