/* Generated By:JJTree: Do not edit this line. ASTArithmeticPrimary.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTArithmeticPrimary extends SimpleNode {

	private String value;

	public ASTArithmeticPrimary(int id) {
		super(id);
	}

	public ASTArithmeticPrimary(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
/* JavaCC - OriginalChecksum=ef8cc4a7b1426908e1528b745e835ad8 (do not edit this line) */
