/* Generated By:JJTree: Do not edit this line. ASTArithmeticExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import java.util.ArrayList;
import java.util.List;

public class ASTArithmeticExpression extends SimpleNode {

	private List<String> signs = new ArrayList<>();
	private String value;

	public ASTArithmeticExpression(int id) {
		super(id);
	}

	public ASTArithmeticExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public List<String> getSigns() {
		return signs;
	}

	public void addSign(String sign) {
		this.signs.add(sign);
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
/* JavaCC - OriginalChecksum=9c941c2632d46788233f89cea4f98e65 (do not edit this line) */
