/* Generated By:JJTree: Do not edit this line. ASTComparisonExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTComparisonExpression extends SimpleNode {

    private String comparisonOperator;

    public ASTComparisonExpression(int id) {
	super(id);
    }

    public ASTComparisonExpression(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getComparisonOperator() {
	return comparisonOperator;
    }

    public void setComparisonOperator(String comparisonOperator) {
	this.comparisonOperator = comparisonOperator;
    }

}
/* JavaCC - OriginalChecksum=365bc291d96e40f5412d3418f78d3f1e (do not edit this line) */
