/* Generated By:JJTree: Do not edit this line. ASTConditionalPrimary.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTConditionalPrimary extends SimpleNode {

    public ASTConditionalPrimary(int id) {
	super(id);
    }

    public ASTConditionalPrimary(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    @Override
    public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
	return children[0].jjtAccept(visitor, data);
    }

}
/* JavaCC - OriginalChecksum=40e163d75c9097c3ff61040a84b86325 (do not edit this line) */
