/* Generated By:JJTree: Do not edit this line. ASTCollectionValuedPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTCollectionValuedPathExpression extends SimpleNode {

    private String collectionValuedField;

    public ASTCollectionValuedPathExpression(int id) {
	super(id);
    }

    public ASTCollectionValuedPathExpression(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getCollectionValuedField() {
	return collectionValuedField;
    }

    public void setCollectionValuedField(String collectionValuedField) {
	this.collectionValuedField = collectionValuedField;
    }

}
/* JavaCC - OriginalChecksum=7ea607cd94f621431e374fa62c2275f3 (do not edit this line) */
