/* Generated By:JJTree: Do not edit this line. ASTCollectionMemberDeclaration.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTCollectionMemberDeclaration extends SimpleNode {

	private String identificationVariable;

	public ASTCollectionMemberDeclaration(int id) {
		super(id);
	}

	public ASTCollectionMemberDeclaration(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

}
/* JavaCC - OriginalChecksum=fdd02be8235384d78684944710adb837 (do not edit this line) */
