/* Generated By:JJTree: Do not edit this line. ASTDatetimeExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.jdbc.db.SqlFunction;

public class ASTDatetimeExpression extends SimpleNode {

	private SqlFunction sqlFunction;
	private String inputParameter;
	private String path;

	public ASTDatetimeExpression(int id) {
		super(id);
	}

	public ASTDatetimeExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public SqlFunction getSqlFunction() {
		return sqlFunction;
	}

	public void setSqlFunction(SqlFunction sqlFunction) {
		this.sqlFunction = sqlFunction;
	}

	public String getInputParameter() {
		return inputParameter;
	}

	public void setInputParameter(String inputParameter) {
		this.inputParameter = inputParameter;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
/* JavaCC - OriginalChecksum=4f475479cae2c07819a1a5e145775209 (do not edit this line) */
