/* Generated By:JJTree: Do not edit this line. ASTFunctionsReturningNumerics.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTFunctionsReturningNumerics extends SimpleNode {
  public ASTFunctionsReturningNumerics(int id) {
    super(id);
  }

  public ASTFunctionsReturningNumerics(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1250de6f2eedd83a14ab281824811bc8 (do not edit this line) */
