/* Generated By:JJTree: Do not edit this line. ASTFunctionArg.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTFunctionArg extends SimpleNode {
  public ASTFunctionArg(int id) {
    super(id);
  }

  public ASTFunctionArg(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d9117c0da8ede9a78bd9cb1f6218890 (do not edit this line) */
