/* Generated By:JJTree: Do not edit this line. ASTGroupbyItem.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTGroupbyItem extends SimpleNode {
	private String identificationVariable;
  public ASTGroupbyItem(int id) {
    super(id);
  }

  public ASTGroupbyItem(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}
  
}
/* JavaCC - OriginalChecksum=431c32abbf3654fdc0876c5d26cb4284 (do not edit this line) */
