/* Generated By:JJTree: Do not edit this line. ASTGeneralCaseExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTGeneralCaseExpression extends SimpleNode {
  public ASTGeneralCaseExpression(int id) {
    super(id);
  }

  public ASTGeneralCaseExpression(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b090daa9d0cd1f9df917f200844cb06 (do not edit this line) */
