/* Generated By:JJTree: Do not edit this line. ASTGroupbyClause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTGroupbyClause extends SimpleNode {
  public ASTGroupbyClause(int id) {
    super(id);
  }

  public ASTGroupbyClause(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=68472bf7f6132cb163ab552acc6c1fc8 (do not edit this line) */
