/* Generated By:JJTree: Do not edit this line. ASTGroupByItem.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTGroupByItem extends SimpleNode {

	private String identificationVariable;

	public ASTGroupByItem(int id) {
		super(id);
	}

	public ASTGroupByItem(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

}
/* JavaCC - OriginalChecksum=1d73d6929aa42c70f04e9fab7ea7dd09 (do not edit this line) */
