/* Generated By:JJTree: Do not edit this line. ASTIndexFunction.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTIndexFunction extends SimpleNode {

	private String identificationVariable;

	public ASTIndexFunction(int id) {
		super(id);
	}

	public ASTIndexFunction(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

}
/* JavaCC - OriginalChecksum=6c1db65c603a23c6b03189b5ff1b85d0 (do not edit this line) */
