/* Generated By:JJTree: Do not edit this line. ASTJoinSingleValuedPathExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTJoinSingleValuedPathExpression extends SimpleNode {
  public ASTJoinSingleValuedPathExpression(int id) {
    super(id);
  }

  public ASTJoinSingleValuedPathExpression(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7c398c488ca638fffbdcbf5e6559d1c0 (do not edit this line) */
