/* Generated By:JJTree: Do not edit this line. ASTJoinSingleValuedPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTJoinSingleValuedPathExpression extends SimpleNode {

	private String identificationVariable;
	private final StringBuilder sb = new StringBuilder();
	private String fieldName;

	public ASTJoinSingleValuedPathExpression(int id) {
		super(id);
	}

	public ASTJoinSingleValuedPathExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

	public void addPath(String path) {
		sb.append(path);
		sb.append(".");
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getPath() {
		return sb.toString();
	}
}
/* JavaCC - OriginalChecksum=7c398c488ca638fffbdcbf5e6559d1c0 (do not edit this line) */
