/* Generated By:JJTree: Do not edit this line. ASTMapFieldIdentificationVariable.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTMapFieldIdentificationVariable extends SimpleNode {

	private final MapFieldIdentificationVariable mapFieldIdentificationVariable = new MapFieldIdentificationVariable();

	public ASTMapFieldIdentificationVariable(int id) {
		super(id);
	}

	public ASTMapFieldIdentificationVariable(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.mapFieldIdentificationVariable.setIdentificationVariable(identificationVariable);
	}

	public MapFieldIdentificationVariable getMapFieldIdentificationVariable() {
		return mapFieldIdentificationVariable;
	}

}
/* JavaCC - OriginalChecksum=550831548f45e9f38870715a0dc647b8 (do not edit this line) */
