/* Generated By:JJTree: Do not edit this line. ASTMapFieldIdentificationVariable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTMapFieldIdentificationVariable extends SimpleNode {
    private boolean key=false;
    private boolean value=false;
    private String identificationVariable;
    
  public ASTMapFieldIdentificationVariable(int id) {
    super(id);
  }

  public ASTMapFieldIdentificationVariable(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

    public boolean isKey() {
	return key;
    }

    public void setKey(boolean key) {
	this.key = key;
    }

    public boolean isValue() {
	return value;
    }

    public void setValue(boolean value) {
	this.value = value;
    }

    public String getIdentificationVariable() {
	return identificationVariable;
    }

    public void setIdentificationVariable(String identificationVariable) {
	this.identificationVariable = identificationVariable;
    }
  
  
}
/* JavaCC - OriginalChecksum=550831548f45e9f38870715a0dc647b8 (do not edit this line) */
