/* Generated By:JJTree: Do not edit this line. ASTNullComparisonExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTNullComparisonExpression extends SimpleNode {

	private String inputParameter;
	private boolean not=false;

	public ASTNullComparisonExpression(int id) {
		super(id);
	}

	public ASTNullComparisonExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getInputParameter() {
		return inputParameter;
	}

	public void setInputParameter(String inputParameter) {
		this.inputParameter = inputParameter;
	}

	public boolean isNot() {
		return not;
	}

	public void setNot(boolean not) {
		this.not = not;
	}

}
/* JavaCC - OriginalChecksum=8e4261a6af1a87a4edb45d95c885614d (do not edit this line) */
