/* Generated By:JJTree: Do not edit this line. ASTSubquery.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTSubquery extends SimpleNode {
  public ASTSubquery(int id) {
    super(id);
  }

  public ASTSubquery(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=044338bb882892f00ffa3eb7d757d5cb (do not edit this line) */
