/* Generated By:JJTree: Do not edit this line. ASTSelectStatement.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSelectStatement extends SimpleNode {

	public ASTSelectStatement(int id) {
		super(id);
	}

	public ASTSelectStatement(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	@Override
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
		for (int i = 0; i < children.length; ++i) {
			if (children[i] instanceof ASTFromClause)
				children[i].jjtAccept(visitor, data);
		}

		for (int i = 0; i < children.length; ++i) {
			if (!(children[i] instanceof ASTFromClause))
				children[i].jjtAccept(visitor, data);
		}

		return data;
	}

}
/* JavaCC - OriginalChecksum=29793356faf64c31d470ab1613b35466 (do not edit this line) */
