/* Generated By:JJTree: Do not edit this line. ASTSimpleCondExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSimpleCondExpression extends SimpleNode {

    public ASTSimpleCondExpression(int id) {
	super(id);
    }

    public ASTSimpleCondExpression(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    @Override
    public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
	return children[0].jjtAccept(visitor, data);
//	if (children != null) {
//	    for (int i = 0; i < children.length; ++i) {
//		children[i].jjtAccept(visitor, data);
//	    }
//	}
//	return data;
    }

}
/* JavaCC - OriginalChecksum=e2f8eb8aaa8c1d4a56c62adce3224ea1 (do not edit this line) */
