/* Generated By:JJTree: Do not edit this line. ASTSelectExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSelectExpression extends SimpleNode {

    private String identificationVariable;

    public ASTSelectExpression(int id) {
	super(id);
    }

    public ASTSelectExpression(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getIdentificationVariable() {
	return identificationVariable;
    }

    public void setIdentificationVariable(String identificationVariable) {
	this.identificationVariable = identificationVariable;
    }

}
/* JavaCC - OriginalChecksum=174844307eed48ffdd41c844b539585c (do not edit this line) */
