/* Generated By:JJTree: Do not edit this line. ASTSingleValuedPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSingleValuedPathExpression extends SimpleNode {

	private String subtype;
	private MapFieldIdentificationVariable mapFieldIdentificationVariable;
	private String identificationVariable;
	private String path;
	private String stateField;

	public ASTSingleValuedPathExpression(int id) {
		super(id);
	}

	public ASTSingleValuedPathExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getSubtype() {
		return subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	public MapFieldIdentificationVariable getMapFieldIdentificationVariable() {
		return mapFieldIdentificationVariable;
	}

	public void setMapFieldIdentificationVariable(MapFieldIdentificationVariable mapFieldIdentificationVariable) {
		this.mapFieldIdentificationVariable = mapFieldIdentificationVariable;
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getStateField() {
		return stateField;
	}

	public void setStateField(String stateField) {
		this.stateField = stateField;
	}

}
/* JavaCC - OriginalChecksum=fd41a8e7dba55103bf5fb17e370790e1 (do not edit this line) */
