/* Generated By:JJTree: Do not edit this line. ASTSelectStatement.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import java.util.ArrayList;
import java.util.List;

public class ASTSelectStatement extends SimpleNode {

	public ASTSelectStatement(int id) {
		super(id);
	}

	public ASTSelectStatement(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	@Override
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

//	@Override
//	public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
//		List<Object> list = new ArrayList<>();
//		if (children != null) {
//			for (int i = 0; i < children.length; ++i) {
//				list.add(children[i].jjtAccept(visitor, data));
//			}
//		}
//
//		return list;
//	}

}
/* JavaCC - OriginalChecksum=29793356faf64c31d470ab1613b35466 (do not edit this line) */
