/* Generated By:JJTree: Do not edit this line. ASTStateFieldPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTStateFieldPathExpression extends SimpleNode {

    private String stateField;

    public ASTStateFieldPathExpression(int id) {
	super(id);
    }

    public ASTStateFieldPathExpression(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getStateField() {
	return stateField;
    }

    public void setStateField(String stateField) {
	this.stateField = stateField;
    }

}
/* JavaCC - OriginalChecksum=009c76941bb3d9b6511e532b3394c873 (do not edit this line) */
