/* Generated By:JJTree: Do not edit this line. ASTSimpleSubpath.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSimpleSubpath extends SimpleNode {

    private StringBuilder sb = new StringBuilder();

    public ASTSimpleSubpath(int id) {
	super(id);
    }

    public ASTSimpleSubpath(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public void addPath(String path) {
	sb.append(".");
	sb.append(path);
    }

    public String getPath() {
	return sb.toString();
    }
}
/* JavaCC - OriginalChecksum=37f9d0138e6587f99d38819c38171296 (do not edit this line) */
