/* Generated By:JJTree: Do not edit this line. ASTSimpleSelectExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSimpleSelectExpression extends SimpleNode {

	private String identificationVariable;

	public ASTSimpleSelectExpression(int id) {
		super(id);
	}

	public ASTSimpleSelectExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

}
/* JavaCC - OriginalChecksum=0c1d99e7b5cc827bd05f94933eaeb68e (do not edit this line) */
