/* Generated By:JJTree: Do not edit this line. ASTSelectClause.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSelectClause extends SimpleNode {

    private boolean distinct = false;

    public ASTSelectClause(int id) {
	super(id);
    }

    public ASTSelectClause(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public void setDistinct(boolean distinct) {
	this.distinct = distinct;
    }

    public boolean isDistinct() {
	return distinct;
    }

}
/* JavaCC - OriginalChecksum=e23ccca0572c8c3cf1d1e5906dd55e64 (do not edit this line) */
