/* Generated By:JJTree: Do not edit this line. ASTStateValuedPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTStateValuedPathExpression extends SimpleNode {

	private String path;

	public ASTStateValuedPathExpression(int id) {
		super(id);
	}

	public ASTStateValuedPathExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
/* JavaCC - OriginalChecksum=9858533906092a69c8f1c630381fc670 (do not edit this line) */
