/* Generated By:JJTree: Do not edit this line. ASTTreatedSubpath.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTTreatedSubpath extends SimpleNode {

    private String subtype;

    public ASTTreatedSubpath(int id) {
	super(id);
    }

    public ASTTreatedSubpath(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getSubtype() {
	return subtype;
    }

    public void setSubtype(String subtype) {
	this.subtype = subtype;
    }

}
/* JavaCC - OriginalChecksum=5f1611b64d42175130c663859b235d34 (do not edit this line) */
