/* Generated By:JJTree: Do not edit this line. ASTTypeDiscriminator.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTTypeDiscriminator extends SimpleNode {

	private String inputParameter;

	public ASTTypeDiscriminator(int id) {
		super(id);
	}

	public ASTTypeDiscriminator(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getInputParameter() {
		return inputParameter;
	}

	public void setInputParameter(String inputParameter) {
		this.inputParameter = inputParameter;
	}

}
/* JavaCC - OriginalChecksum=30119faaabce150151e765a2e06cf13d (do not edit this line) */
