/* Generated By:JJTree: Do not edit this line. ASTWhereClause.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTWhereClause extends SimpleNode {

    public ASTWhereClause(int id) {
	super(id);
    }

    public ASTWhereClause(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    @Override
    public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
	return children[0].jjtAccept(visitor, data);
    }

}
/* JavaCC - OriginalChecksum=1f6b057cfeb9cb26469d5711748a8ae8 (do not edit this line) */
