/* Generated By:JavaCC: Do not edit this line. JpqlParserTreeConstants.java Version 7.0.10 */
package org.minijpa.jpa.jpql;

public interface JpqlParserTreeConstants
{
  public int JJTQLSTATEMENT = 0;
  public int JJTSELECTSTATEMENT = 1;
  public int JJTSELECTCLAUSE = 2;
  public int JJTSELECTITEM = 3;
  public int JJTSELECTEXPRESSION = 4;
  public int JJTVOID = 5;
  public int JJTJOINSINGLEVALUEDPATHEXPRESSION = 6;
  public int JJTSUBTYPE = 7;
  public int JJTJOINASSOCIATIONPATHEXPRESSION = 8;
  public int JJTJOIN = 9;
  public int JJTRANGEVARIABLEDECLARATION = 10;
  public int JJTIDENTIFICATIONVARIABLEDECLARATION = 11;
  public int JJTFROMCLAUSE = 12;
  public int JJTMAPFIELDIDENTIFICATIONVARIABLE = 13;
  public int JJTGENERALIDENTIFICATIONVARIABLE = 14;
  public int JJTSIMPLESUBPATH = 15;
  public int JJTGENERALSUBPATH = 16;
  public int JJTTREATEDSUBPATH = 17;
  public int JJTSTATEFIELDPATHEXPRESSION = 18;
  public int JJTSTATEVALUEDPATHEXPRESSION = 19;
  public int JJTSINGLEVALUEDOBJECTPATHEXPRESSION = 20;
  public int JJTWHENCLAUSE = 21;
  public int JJTSTRINGEXPRESSION = 22;
  public int JJTCOMPARISONEXPRESSION = 23;
  public int JJTCOLLECTIONVALUEDPATHEXPRESSION = 24;
  public int JJTSIMPLECONDEXPRESSION = 25;
  public int JJTCONDITIONALPRIMARY = 26;
  public int JJTCONDITIONALFACTOR = 27;
  public int JJTCONDITIONALTERM = 28;
  public int JJTCONDITIONALEXPRESSION = 29;
  public int JJTWHERECLAUSE = 30;
  public int JJTHAVINGCLAUSE = 31;


  public String[] jjtNodeName = {
    "QLStatement",
    "SelectStatement",
    "SelectClause",
    "SelectItem",
    "SelectExpression",
    "void",
    "JoinSingleValuedPathExpression",
    "Subtype",
    "JoinAssociationPathExpression",
    "Join",
    "RangeVariableDeclaration",
    "IdentificationVariableDeclaration",
    "FromClause",
    "MapFieldIdentificationVariable",
    "GeneralIdentificationVariable",
    "SimpleSubpath",
    "GeneralSubpath",
    "TreatedSubpath",
    "StateFieldPathExpression",
    "StateValuedPathExpression",
    "SingleValuedObjectPathExpression",
    "WhenClause",
    "StringExpression",
    "ComparisonExpression",
    "CollectionValuedPathExpression",
    "SimpleCondExpression",
    "ConditionalPrimary",
    "ConditionalFactor",
    "ConditionalTerm",
    "ConditionalExpression",
    "WhereClause",
    "HavingClause",
  };
}
/* JavaCC - OriginalChecksum=e2bcc537e6952b3a45818501335f8910 (do not edit this line) */
