/* Generated By:JavaCC: Do not edit this line. JpqlParserVisitor.java Version 7.0.10 */
package org.minijpa.jpa.jpql;

public interface JpqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTQLStatement node, Object data);
  public Object visit(ASTSelectStatement node, Object data);
  public Object visit(ASTSelectClause node, Object data);
  public Object visit(ASTSelectItem node, Object data);
  public Object visit(ASTSelectExpression node, Object data);
  public Object visit(ASTJoinSingleValuedPathExpression node, Object data);
  public Object visit(ASTSubtype node, Object data);
  public Object visit(ASTJoinAssociationPathExpression node, Object data);
  public Object visit(ASTJoin node, Object data);
  public Object visit(ASTRangeVariableDeclaration node, Object data);
  public Object visit(ASTIdentificationVariableDeclaration node, Object data);
  public Object visit(ASTFromClause node, Object data);
}
/* JavaCC - OriginalChecksum=06f9f52ef94deb9a3f18585e05acbc68 (do not edit this line) */
