/* Generated By:JJTree: Do not edit this line. ASTArithmeticBetweenExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.sql.model.condition.Condition;

public class ASTArithmeticBetweenExpression extends SimpleNode implements ConditionNode {

	private boolean not = false;
	private Condition condition;

	public ASTArithmeticBetweenExpression(int id) {
		super(id);
	}

	public ASTArithmeticBetweenExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public boolean isNot() {
		return not;
	}

	public void setNot(boolean not) {
		this.not = not;
	}

	@Override
	public Condition getCondition() {
		return condition;
	}

	@Override
	public void setCondition(Condition condition) {
		this.condition = condition;
	}

}
/* JavaCC - OriginalChecksum=45636124662f6ef6738c85894e980815 (do not edit this line) */
