/* Generated By:JJTree: Do not edit this line. ASTBetweenExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.sql.model.condition.Condition;

public class ASTBetweenExpression extends SimpleNode implements ConditionNode {

	private Condition condition;

	public ASTBetweenExpression(int id) {
		super(id);
	}

	public ASTBetweenExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	@Override
	public Condition getCondition() {
		return condition;
	}

	@Override
	public void setCondition(Condition condition) {
		this.condition = condition;
	}

}
/* JavaCC - OriginalChecksum=66729f15768b578dd3884dcc234b95fd (do not edit this line) */
