/* Generated By:JJTree: Do not edit this line. ASTConcatFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTConcatFunction extends SimpleNode {
  public ASTConcatFunction(int id) {
    super(id);
  }

  public ASTConcatFunction(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0c9d19628e38a2364b3fc1c00557cbb (do not edit this line) */
