/* Generated By:JJTree: Do not edit this line. ASTEntityTypeExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTEntityTypeExpression extends SimpleNode {
  public ASTEntityTypeExpression(int id) {
    super(id);
  }

  public ASTEntityTypeExpression(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2489c27994b786b8a338976bf11b5b7b (do not edit this line) */
