/* Generated By:JJTree: Do not edit this line. ASTFunctionInvocation.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTFunctionInvocation extends SimpleNode {

	private String functionName;

	public ASTFunctionInvocation(int id) {
		super(id);
	}

	public ASTFunctionInvocation(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

}
/* JavaCC - OriginalChecksum=a80d5d2007233b3ef3551339d1cac3ed (do not edit this line) */
