/* Generated By:JJTree: Do not edit this line. ASTGeneralSubpath.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTGeneralSubpath extends SimpleNode {

	private final StringBuilder sb = new StringBuilder();
	private MapFieldIdentificationVariable mapFieldIdentificationVariable;
	private String identificationVariable;
	private String path;

	public ASTGeneralSubpath(int id) {
		super(id);
	}

	public ASTGeneralSubpath(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public void addPath(String path) {
		sb.append(".");
		sb.append(path);
	}

	public String getTreatedPath() {
		return sb.toString();
	}

	public MapFieldIdentificationVariable getMapFieldIdentificationVariable() {
		return mapFieldIdentificationVariable;
	}

	public void setMapFieldIdentificationVariable(MapFieldIdentificationVariable mapFieldIdentificationVariable) {
		this.mapFieldIdentificationVariable = mapFieldIdentificationVariable;
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getPath() {
		return path;
	}
}
/* JavaCC - OriginalChecksum=f0dd85c1a2fd54d2f4d26be6560888b3 (do not edit this line) */
