/* Generated By:JJTree: Do not edit this line. ASTGeneralDerivedPath.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTGeneralDerivedPath extends SimpleNode {

	private StringBuilder sb = new StringBuilder();

	public ASTGeneralDerivedPath(int id) {
		super(id);
	}

	public ASTGeneralDerivedPath(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public void addPath(String path) {
		if (sb.length() > 0)
			sb.append(".");

		sb.append(path);
	}

	public String getpath() {
		return sb.toString();
	}

}
/* JavaCC - OriginalChecksum=3b48bf1a326b3dbecd9feefaaf8a3474 (do not edit this line) */
