/* Generated By:JJTree: Do not edit this line. ASTJoin.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTJoin extends SimpleNode {

    private JoinType joinType;
    private String identificationVariable;

    public ASTJoin(int id) {
        super(id);
    }

    public ASTJoin(JpqlParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

        return visitor.visit(this, data);
    }

    public JoinType getJoinType() {
        return joinType;
    }

    public void setJoinType(JoinType joinType) {
        this.joinType = joinType;
    }

    public String getIdentificationVariable() {
        return identificationVariable;
    }

    public void setIdentificationVariable(String identificationVariable) {
        this.identificationVariable = identificationVariable;
    }

}
/* JavaCC - OriginalChecksum=000f6b63a166590a9d068fac5d20e40c (do not edit this line) */
