/* Generated By:JJTree: Do not edit this line. ASTLocateFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTLocateFunction extends SimpleNode {
  public ASTLocateFunction(int id) {
    super(id);
  }

  public ASTLocateFunction(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=491d9b16a0eca69018f0b1b0ea7acf02 (do not edit this line) */
