/* Generated By:JJTree: Do not edit this line. ASTRangeVariableDeclaration.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTRangeVariableDeclaration extends SimpleNode {

    private String entityName;
    private String alias;

    public ASTRangeVariableDeclaration(int id) {
	super(id);
    }

    public ASTRangeVariableDeclaration(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getEntityName() {
	return entityName;
    }

    public void setEntityName(String entityName) {
	this.entityName = entityName;
    }

    public String getAlias() {
	return alias;
    }

    public void setAlias(String alias) {
	this.alias = alias;
    }

}
/* JavaCC - OriginalChecksum=9808ad06ff5bf3cf4c795698ea547f9d (do not edit this line) */
