/* Generated By:JJTree: Do not edit this line. ASTSubstringFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTSubstringFunction extends SimpleNode {
  public ASTSubstringFunction(int id) {
    super(id);
  }

  public ASTSubstringFunction(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ded2c0a03330ff6b0f872c4ac4ab9f99 (do not edit this line) */
