/* Generated By:JJTree: Do not edit this line. ASTSelectItem.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSelectItem extends SimpleNode {

    private String alias;

    public ASTSelectItem(int id) {
	super(id);
    }

    public ASTSelectItem(JpqlParser p, int id) {
	super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

	return visitor.visit(this, data);
    }

    public String getAlias() {
	return alias;
    }

    public void setAlias(String alias) {
	this.alias = alias;
    }

}
/* JavaCC - OriginalChecksum=2ba47207f4902bd1588bfc30bbad1872 (do not edit this line) */
