/* Generated By:JJTree: Do not edit this line. ASTSubqueryFromClause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTSubqueryFromClause extends SimpleNode {
  public ASTSubqueryFromClause(int id) {
    super(id);
  }

  public ASTSubqueryFromClause(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b6e223083e022551ed5a5d93f52e367 (do not edit this line) */
