/* Generated By:JJTree: Do not edit this line. ASTSimpleSelectClause.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSimpleSelectClause extends SimpleNode {

	private boolean distinct = false;

	public ASTSimpleSelectClause(int id) {
		super(id);
	}

	public ASTSimpleSelectClause(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public boolean isDistinct() {
		return distinct;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

}
/* JavaCC - OriginalChecksum=3fe811ae36e7075cae3feab05b5062d0 (do not edit this line) */
