/* Generated By:JJTree: Do not edit this line. ASTTreatedDerivedPath.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTTreatedDerivedPath extends SimpleNode {
  public ASTTreatedDerivedPath(int id) {
    super(id);
  }

  public ASTTreatedDerivedPath(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4b76da86bded9ff339408f6dfab240dc (do not edit this line) */
