/* Generated By:JavaCC: Do not edit this line. JpqlParserTreeConstants.java Version 4.1d1 */
package org.minijpa.jpa.jpql;

public interface JpqlParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTQLSTATEMENT = 1;
  public int JJTSELECTSTATEMENT = 2;
  public int JJTSELECTCLAUSE = 3;
  public int JJTSELECTITEM = 4;
  public int JJTSELECTEXPRESSION = 5;
  public int JJTCONSTRUCTORITEM = 6;
  public int JJTCONSTRUCTOREXPRESSION = 7;
  public int JJTJOINSINGLEVALUEDPATHEXPRESSION = 8;
  public int JJTSUBTYPE = 9;
  public int JJTJOINASSOCIATIONPATHEXPRESSION = 10;
  public int JJTJOIN = 11;
  public int JJTFETCHJOIN = 12;
  public int JJTRANGEVARIABLEDECLARATION = 13;
  public int JJTIDENTIFICATIONVARIABLEDECLARATION = 14;
  public int JJTFROMCLAUSE = 15;
  public int JJTMAPFIELDIDENTIFICATIONVARIABLE = 16;
  public int JJTQUALIFIEDIDENTIFICATIONVARIABLE = 17;
  public int JJTGENERALIDENTIFICATIONVARIABLE = 18;
  public int JJTSIMPLESUBPATH = 19;
  public int JJTGENERALSUBPATH = 20;
  public int JJTTREATEDSUBPATH = 21;
  public int JJTSTATEFIELDPATHEXPRESSION = 22;
  public int JJTSTATEVALUEDPATHEXPRESSION = 23;
  public int JJTFUNCTIONSRETURNINGSTRINGS = 24;
  public int JJTCONCATFUNCTION = 25;
  public int JJTSUBSTRINGFUNCTION = 26;
  public int JJTTRIMFUNCTION = 27;
  public int JJTLOWERFUNCTION = 28;
  public int JJTUPPERFUNCTION = 29;
  public int JJTFUNCTIONSRETURNINGNUMERICS = 30;
  public int JJTLENGTHFUNCTION = 31;
  public int JJTLOCATEFUNCTION = 32;
  public int JJTABSFUNCTION = 33;
  public int JJTSQRTFUNCTION = 34;
  public int JJTMODFUNCTION = 35;
  public int JJTSIZEFUNCTION = 36;
  public int JJTINDEXFUNCTION = 37;
  public int JJTSINGLEVALUEDOBJECTPATHEXPRESSION = 38;
  public int JJTAGGREGATEEXPRESSION = 39;
  public int JJTFUNCTIONINVOCATION = 40;
  public int JJTFUNCTIONARG = 41;
  public int JJTSCALAREXPRESSION = 42;
  public int JJTTYPEDISCRIMINATOR = 43;
  public int JJTWHENCLAUSE = 44;
  public int JJTGENERALCASEEXPRESSION = 45;
  public int JJTCASEEXPRESSION = 46;
  public int JJTENTITYTYPEEXPRESSION = 47;
  public int JJTENUMEXPRESSION = 48;
  public int JJTBOOLEANEXPRESSION = 49;
  public int JJTDATETIMEEXPRESSION = 50;
  public int JJTSTRINGEXPRESSION = 51;
  public int JJTARITHMETICPRIMARY = 52;
  public int JJTARITHMETICFACTOR = 53;
  public int JJTARITHMETICTERM = 54;
  public int JJTARITHMETICEXPRESSION = 55;
  public int JJTALLORANYEXPRESSION = 56;
  public int JJTSTRINGEXPRESSIONCOMPARISON = 57;
  public int JJTARITHMETICEXPRESSIONCOMPARISON = 58;
  public int JJTBOOLEANEXPRESSIONCOMPARISON = 59;
  public int JJTDATETIMEEXPRESSIONCOMPARISON = 60;
  public int JJTENTITYTYPEEXPRESSIONCOMPARISON = 61;
  public int JJTCOMPARISONEXPRESSION = 62;
  public int JJTEXISTSEXPRESSION = 63;
  public int JJTENTITYORVALUEEXPRESSION = 64;
  public int JJTCOLLECTIONVALUEDPATHEXPRESSION = 65;
  public int JJTCOLLECTIONMEMBEREXPRESSION = 66;
  public int JJTEMPTYCOLLECTIONCOMPARISONEXPRESSION = 67;
  public int JJTNULLCOMPARISONEXPRESSION = 68;
  public int JJTLIKEEXPRESSION = 69;
  public int JJTINITEM = 70;
  public int JJTINEXPRESSION = 71;
  public int JJTBETWEENEXPRESSION = 72;
  public int JJTARITHMETICBETWEENEXPRESSION = 73;
  public int JJTSTRINGBETWEENEXPRESSION = 74;
  public int JJTDATETIMEBETWEENEXPRESSION = 75;
  public int JJTSIMPLECONDEXPRESSION = 76;
  public int JJTCONDITIONALPRIMARY = 77;
  public int JJTCONDITIONALFACTOR = 78;
  public int JJTCONDITIONALTERM = 79;
  public int JJTCONDITIONALEXPRESSION = 80;
  public int JJTWHERECLAUSE = 81;
  public int JJTSINGLEVALUEDPATHEXPRESSION = 82;
  public int JJTSIMPLESELECTEXPRESSION = 83;
  public int JJTSIMPLESELECTCLAUSE = 84;
  public int JJTDERIVEDCOLLECTIONMEMBERDECLARATION = 85;
  public int JJTTREATEDDERIVEDPATH = 86;
  public int JJTSIMPLEDERIVEDPATH = 87;
  public int JJTGENERALDERIVEDPATH = 88;
  public int JJTDERIVEDPATHEXPRESSION = 89;
  public int JJTSUBSELECTIDENTIFICATIONVARIABLEDECLARATION = 90;
  public int JJTSUBQUERYFROMCLAUSE = 91;
  public int JJTCOLLECTIONMEMBERDECLARATION = 92;
  public int JJTSUBQUERY = 93;
  public int JJTORDERBYITEM = 94;
  public int JJTORDERBYCLAUSE = 95;
  public int JJTHAVINGCLAUSE = 96;
  public int JJTGROUPBYITEM = 97;
  public int JJTGROUPBYCLAUSE = 98;


  public String[] jjtNodeName = {
    "void",
    "QLStatement",
    "SelectStatement",
    "SelectClause",
    "SelectItem",
    "SelectExpression",
    "ConstructorItem",
    "ConstructorExpression",
    "JoinSingleValuedPathExpression",
    "Subtype",
    "JoinAssociationPathExpression",
    "Join",
    "FetchJoin",
    "RangeVariableDeclaration",
    "IdentificationVariableDeclaration",
    "FromClause",
    "MapFieldIdentificationVariable",
    "QualifiedIdentificationVariable",
    "GeneralIdentificationVariable",
    "SimpleSubpath",
    "GeneralSubpath",
    "TreatedSubpath",
    "StateFieldPathExpression",
    "StateValuedPathExpression",
    "FunctionsReturningStrings",
    "ConcatFunction",
    "SubstringFunction",
    "TrimFunction",
    "LowerFunction",
    "UpperFunction",
    "FunctionsReturningNumerics",
    "LengthFunction",
    "LocateFunction",
    "AbsFunction",
    "SqrtFunction",
    "ModFunction",
    "SizeFunction",
    "IndexFunction",
    "SingleValuedObjectPathExpression",
    "AggregateExpression",
    "FunctionInvocation",
    "FunctionArg",
    "ScalarExpression",
    "TypeDiscriminator",
    "WhenClause",
    "GeneralCaseExpression",
    "CaseExpression",
    "EntityTypeExpression",
    "EnumExpression",
    "BooleanExpression",
    "DatetimeExpression",
    "StringExpression",
    "ArithmeticPrimary",
    "ArithmeticFactor",
    "ArithmeticTerm",
    "ArithmeticExpression",
    "AllOrAnyExpression",
    "StringExpressionComparison",
    "ArithmeticExpressionComparison",
    "BooleanExpressionComparison",
    "DatetimeExpressionComparison",
    "EntityTypeExpressionComparison",
    "ComparisonExpression",
    "ExistsExpression",
    "EntityOrValueExpression",
    "CollectionValuedPathExpression",
    "CollectionMemberExpression",
    "EmptyCollectionComparisonExpression",
    "NullComparisonExpression",
    "LikeExpression",
    "InItem",
    "InExpression",
    "BetweenExpression",
    "ArithmeticBetweenExpression",
    "StringBetweenExpression",
    "DatetimeBetweenExpression",
    "SimpleCondExpression",
    "ConditionalPrimary",
    "ConditionalFactor",
    "ConditionalTerm",
    "ConditionalExpression",
    "WhereClause",
    "SingleValuedPathExpression",
    "SimpleSelectExpression",
    "SimpleSelectClause",
    "DerivedCollectionMemberDeclaration",
    "TreatedDerivedPath",
    "SimpleDerivedPath",
    "GeneralDerivedPath",
    "DerivedPathExpression",
    "SubselectIdentificationVariableDeclaration",
    "SubqueryFromClause",
    "CollectionMemberDeclaration",
    "Subquery",
    "OrderByItem",
    "OrderByClause",
    "HavingClause",
    "GroupByItem",
    "GroupByClause",
  };
}
/* JavaCC - OriginalChecksum=642139ea8afd49b837ea3b46a9b4b6cd (do not edit this line) */
