package org.minijpa.jpa.criteria;

public enum PredicateType {
	EQUAL, NOT_EQUAL, OR, AND, NOT, IS_NULL, IS_NOT_NULL, IS_TRUE, IS_FALSE, EMPTY_CONJUNCTION, EMPTY_DISJUNCTION,
	GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, GT, LESS_THAN, LESS_THAN_OR_EQUAL_TO, LT, BETWEEN_EXPRESSIONS,
	BETWEEN_VALUES, LIKE_PATTERN, LIKE_PATTERN_EXPR;

}
