package org.minijpa.jpa.criteria;

public enum PredicateType {
	EQUAL, NOT_EQUAL, OR, AND, NOT, IS_NULL, IS_NOT_NULL, IS_TRUE, IS_FALSE, EMPTY_CONJUNCTION, EMPTY_DISJUNCTION,
	GREATER_THAN, GT, LESS_THAN, LT, BETWEEN_EXPRESSIONS, BETWEEN_VALUES, LIKE_PATTERN, LIKE_PATTERN_EXPR;

}
