/* Generated By:JJTree: Do not edit this line. ASTConditionalPrimary.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.sql.model.condition.Condition;

public class ASTConditionalPrimary extends SimpleNode {

	private Condition condition;

	public ASTConditionalPrimary(int id) {
		super(id);
	}

	public ASTConditionalPrimary(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public Condition getCondition() {
		return condition;
	}

	public void setCondition(Condition condition) {
		this.condition = condition;
	}

}
/* JavaCC - OriginalChecksum=40e163d75c9097c3ff61040a84b86325 (do not edit this line) */
