/* Generated By:JJTree: Do not edit this line. ASTConditionalTerm.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.sql.model.condition.Condition;

public class ASTConditionalTerm extends SimpleNode {

	private Condition condition;

	public ASTConditionalTerm(int id) {
		super(id);
	}

	public ASTConditionalTerm(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public Condition getCondition() {
		return condition;
	}

	public void setCondition(Condition condition) {
		this.condition = condition;
	}
}
/* JavaCC - OriginalChecksum=08595c5aec453ebce82822aa5a49ce2c (do not edit this line) */
