/* Generated By:JJTree: Do not edit this line. ASTDerivedPathExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTDerivedPathExpression extends SimpleNode {

	private String field;

	public ASTDerivedPathExpression(int id) {
		super(id);
	}

	public ASTDerivedPathExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getField() {
		return field;
	}

	public void setField(String field) {
		this.field = field;
	}

}
/* JavaCC - OriginalChecksum=4bf64c0932e7e487a51df5d80fc83059 (do not edit this line) */
