/* Generated By:JJTree: Do not edit this line. ASTFunctionsReturningStrings.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public
class ASTFunctionsReturningStrings extends SimpleNode {
  public ASTFunctionsReturningStrings(int id) {
    super(id);
  }

  public ASTFunctionsReturningStrings(JpqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1626ff21e2a6002f18eff03ef11d97f5 (do not edit this line) */
