/* Generated By:JJTree: Do not edit this line. ASTFetchJoin.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTFetchJoin extends SimpleNode {

	private JoinType joinType;

	public ASTFetchJoin(int id) {
		super(id);
	}

	public ASTFetchJoin(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public JoinType getJoinType() {
		return joinType;
	}

	public void setJoinType(JoinType joinType) {
		this.joinType = joinType;
	}

}
/* JavaCC - OriginalChecksum=2b04295e2ef8073226627960c6de5d30 (do not edit this line) */
