/* Generated By:JJTree: Do not edit this line. ASTOrderByItem.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.sql.model.OrderByType;

public class ASTOrderByItem extends SimpleNode {

	private String resultVariable;
	private OrderByType orderByType;

	public ASTOrderByItem(int id) {
		super(id);
	}

	public ASTOrderByItem(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getResultVariable() {
		return resultVariable;
	}

	public void setResultVariable(String resultVariable) {
		this.resultVariable = resultVariable;
	}

	public OrderByType getOrderByType() {
		return orderByType;
	}

	public void setOrderByType(OrderByType orderByType) {
		this.orderByType = orderByType;
	}

}
/* JavaCC - OriginalChecksum=f2f8fb5c367a333e7938821657c8dd04 (do not edit this line) */
