/* Generated By:JJTree: Do not edit this line. ASTScalarExpression.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.jdbc.model.Value;

public class ASTScalarExpression extends SimpleNode {

	private Value value;

	public ASTScalarExpression(int id) {
		super(id);
	}

	public ASTScalarExpression(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public Value getValue() {
		return value;
	}

	public void setValue(Value value) {
		this.value = value;
	}

}
/* JavaCC - OriginalChecksum=d6f220b332d92aef6625e5cfc4fd0947 (do not edit this line) */
