/* Generated By:JJTree: Do not edit this line. ASTSubselectIdentificationVariableDeclaration.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSubselectIdentificationVariableDeclaration extends SimpleNode {

	private String entityAlias;

	public ASTSubselectIdentificationVariableDeclaration(int id) {
		super(id);
	}

	public ASTSubselectIdentificationVariableDeclaration(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getEntityAlias() {
		return entityAlias;
	}

	public void setEntityAlias(String entityAlias) {
		this.entityAlias = entityAlias;
	}

}
/* JavaCC - OriginalChecksum=7d0a7f08ffe6fd6a057bfdb4b4f9ddc6 (do not edit this line) */
