/* Generated By:JJTree: Do not edit this line. ASTSubquery.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.jdbc.db.SqlSelectData;

public class ASTSubquery extends SimpleNode {

	private SqlSelectData sqlSelectData;

	public ASTSubquery(int id) {
		super(id);
	}

	public ASTSubquery(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	@Override
	public Object childrenAccept(JpqlParserVisitor visitor, Object data) {
		for (int i = 0; i < children.length; ++i) {
			if (children[i] instanceof ASTSubqueryFromClause)
				children[i].jjtAccept(visitor, data);
		}

		for (int i = 0; i < children.length; ++i) {
			if (!(children[i] instanceof ASTSubqueryFromClause))
				children[i].jjtAccept(visitor, data);
		}

		return data;
	}

	public SqlSelectData getSqlSelectData() {
		return sqlSelectData;
	}

	public void setSqlSelectData(SqlSelectData sqlSelectData) {
		this.sqlSelectData = sqlSelectData;
	}

}
/*
 * JavaCC - OriginalChecksum=044338bb882892f00ffa3eb7d757d5cb (do not edit this
 * line)
 */
