/* Generated By:JJTree: Do not edit this line. ASTSimpleDerivedPath.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

public class ASTSimpleDerivedPath extends SimpleNode {

	private String identificationVariable;
	private StringBuilder sb = new StringBuilder();

	public ASTSimpleDerivedPath(int id) {
		super(id);
	}

	public ASTSimpleDerivedPath(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public String getIdentificationVariable() {
		return identificationVariable;
	}

	public void setIdentificationVariable(String identificationVariable) {
		this.identificationVariable = identificationVariable;
	}

	public void addPath(String path) {
		if (sb.length() > 0)
			sb.append(".");

		sb.append(path);
	}

	public String getpath() {
		return sb.toString();
	}

}
/* JavaCC - OriginalChecksum=2a0799d7cfa14b63a7c0cd60a1b5899f (do not edit this line) */
