/* Generated By:JJTree: Do not edit this line. ASTTrimFunction.java Version 7.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.minijpa.jpa.jpql;

import org.minijpa.jdbc.model.function.TrimType;

public class ASTTrimFunction extends SimpleNode {

	private TrimType trimType;
	private String trimCharacter;

	public ASTTrimFunction(int id) {
		super(id);
	}

	public ASTTrimFunction(JpqlParser p, int id) {
		super(p, id);
	}

	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(JpqlParserVisitor visitor, Object data) {

		return visitor.visit(this, data);
	}

	public TrimType getTrimType() {
		return trimType;
	}

	public void setTrimType(TrimType trimType) {
		this.trimType = trimType;
	}

	public String getTrimCharacter() {
		return trimCharacter;
	}

	public void setTrimCharacter(String trimCharacter) {
		this.trimCharacter = trimCharacter;
	}

}
/* JavaCC - OriginalChecksum=fd3e2aa3cce1997c43f674adcc21e745 (do not edit this line) */
